# Generated by Django 4.0.1 on 2022-01-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_up',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
